apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterName }}-hyena
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: hyena
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
  {{- if .Values.store.service.annotations }}
  annotations:
{{ toYaml .Values.store.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.store.service.type }}
  {{- if .Values.store.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.store.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.store.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.store.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: hyena-port
    port: 9527
    targetPort: 9527
    protocol: TCP
  - name: raft-port
    port: 9528
    targetPort: 9528
    protocol: TCP
  - name: prophet-port
    port: 9529
    targetPort: 9529
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    #app.kubernetes.io/component: proxy
