/*
Copyright The infinivision Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/infinivision/hyena-operator/pkg/apis/infinivision.com/v1alpha1"
	scheme "github.com/infinivision/hyena-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HyenaClustersGetter has a method to return a HyenaClusterInterface.
// A group's client should implement this interface.
type HyenaClustersGetter interface {
	HyenaClusters(namespace string) HyenaClusterInterface
}

// HyenaClusterInterface has methods to work with HyenaCluster resources.
type HyenaClusterInterface interface {
	Create(*v1alpha1.HyenaCluster) (*v1alpha1.HyenaCluster, error)
	Update(*v1alpha1.HyenaCluster) (*v1alpha1.HyenaCluster, error)
	UpdateStatus(*v1alpha1.HyenaCluster) (*v1alpha1.HyenaCluster, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.HyenaCluster, error)
	List(opts v1.ListOptions) (*v1alpha1.HyenaClusterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.HyenaCluster, err error)
	HyenaClusterExpansion
}

// hyenaClusters implements HyenaClusterInterface
type hyenaClusters struct {
	client rest.Interface
	ns     string
}

// newHyenaClusters returns a HyenaClusters
func newHyenaClusters(c *InfinivisionV1alpha1Client, namespace string) *hyenaClusters {
	return &hyenaClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hyenaCluster, and returns the corresponding hyenaCluster object, and an error if there is any.
func (c *hyenaClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.HyenaCluster, err error) {
	result = &v1alpha1.HyenaCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hyenaclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HyenaClusters that match those selectors.
func (c *hyenaClusters) List(opts v1.ListOptions) (result *v1alpha1.HyenaClusterList, err error) {
	result = &v1alpha1.HyenaClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hyenaclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hyenaClusters.
func (c *hyenaClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hyenaclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a hyenaCluster and creates it.  Returns the server's representation of the hyenaCluster, and an error, if there is any.
func (c *hyenaClusters) Create(hyenaCluster *v1alpha1.HyenaCluster) (result *v1alpha1.HyenaCluster, err error) {
	result = &v1alpha1.HyenaCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hyenaclusters").
		Body(hyenaCluster).
		Do().
		Into(result)
	return
}

// Update takes the representation of a hyenaCluster and updates it. Returns the server's representation of the hyenaCluster, and an error, if there is any.
func (c *hyenaClusters) Update(hyenaCluster *v1alpha1.HyenaCluster) (result *v1alpha1.HyenaCluster, err error) {
	result = &v1alpha1.HyenaCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hyenaclusters").
		Name(hyenaCluster.Name).
		Body(hyenaCluster).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *hyenaClusters) UpdateStatus(hyenaCluster *v1alpha1.HyenaCluster) (result *v1alpha1.HyenaCluster, err error) {
	result = &v1alpha1.HyenaCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hyenaclusters").
		Name(hyenaCluster.Name).
		SubResource("status").
		Body(hyenaCluster).
		Do().
		Into(result)
	return
}

// Delete takes name of the hyenaCluster and deletes it. Returns an error if one occurs.
func (c *hyenaClusters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hyenaclusters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hyenaClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hyenaclusters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched hyenaCluster.
func (c *hyenaClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.HyenaCluster, err error) {
	result = &v1alpha1.HyenaCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hyenaclusters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
