# Default values for hyena-operator

# clusterScoped is whether hyena-operator should manage kubernetes cluster wide hyena clusters
# Also see rbac.create and controllerManager.serviceAccount
clusterScoped: true

# Also see clusterScoped and controllerManager.serviceAccount
rbac:
  create: true

# operatorImage is Hyena Operator image
operatorImage: infinivision/hyena-operator:latest
imagePullPolicy: Always

defaultStorageClassName: local-storage

controllerManager:
  # With rbac.create=false, the user is responsible for creating this account
  # With rbac.create=true, this service account will be created
  # Also see rbac.create and clusterScoped
  serviceAccount: hyena-controller-manager
  logLevel: 6
  replicas: 1
  resources:
    limits:
      cpu: 250m
      memory: 150Mi
    requests:
      cpu: 80m
      memory: 50Mi
