/*
Copyright The infinivision Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/infinivision/hyena-operator/pkg/apis/infinivision.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHyenaClusters implements HyenaClusterInterface
type FakeHyenaClusters struct {
	Fake *FakeInfinivisionV1alpha1
	ns   string
}

var hyenaclustersResource = schema.GroupVersionResource{Group: "infinivision.com", Version: "v1alpha1", Resource: "hyenaclusters"}

var hyenaclustersKind = schema.GroupVersionKind{Group: "infinivision.com", Version: "v1alpha1", Kind: "HyenaCluster"}

// Get takes name of the hyenaCluster, and returns the corresponding hyenaCluster object, and an error if there is any.
func (c *FakeHyenaClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.HyenaCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hyenaclustersResource, c.ns, name), &v1alpha1.HyenaCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HyenaCluster), err
}

// List takes label and field selectors, and returns the list of HyenaClusters that match those selectors.
func (c *FakeHyenaClusters) List(opts v1.ListOptions) (result *v1alpha1.HyenaClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hyenaclustersResource, hyenaclustersKind, c.ns, opts), &v1alpha1.HyenaClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HyenaClusterList{}
	for _, item := range obj.(*v1alpha1.HyenaClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hyenaClusters.
func (c *FakeHyenaClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hyenaclustersResource, c.ns, opts))

}

// Create takes the representation of a hyenaCluster and creates it.  Returns the server's representation of the hyenaCluster, and an error, if there is any.
func (c *FakeHyenaClusters) Create(hyenaCluster *v1alpha1.HyenaCluster) (result *v1alpha1.HyenaCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hyenaclustersResource, c.ns, hyenaCluster), &v1alpha1.HyenaCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HyenaCluster), err
}

// Update takes the representation of a hyenaCluster and updates it. Returns the server's representation of the hyenaCluster, and an error, if there is any.
func (c *FakeHyenaClusters) Update(hyenaCluster *v1alpha1.HyenaCluster) (result *v1alpha1.HyenaCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hyenaclustersResource, c.ns, hyenaCluster), &v1alpha1.HyenaCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HyenaCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHyenaClusters) UpdateStatus(hyenaCluster *v1alpha1.HyenaCluster) (*v1alpha1.HyenaCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hyenaclustersResource, "status", c.ns, hyenaCluster), &v1alpha1.HyenaCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HyenaCluster), err
}

// Delete takes name of the hyenaCluster and deletes it. Returns an error if one occurs.
func (c *FakeHyenaClusters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hyenaclustersResource, c.ns, name), &v1alpha1.HyenaCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHyenaClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hyenaclustersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.HyenaClusterList{})
	return err
}

// Patch applies the patch and returns the patched hyenaCluster.
func (c *FakeHyenaClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.HyenaCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hyenaclustersResource, c.ns, name, data, subresources...), &v1alpha1.HyenaCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HyenaCluster), err
}
