/*
Copyright The infinivision Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	infinivisioncomv1alpha1 "github.com/infinivision/hyena-operator/pkg/apis/infinivision.com/v1alpha1"
	versioned "github.com/infinivision/hyena-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/infinivision/hyena-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/infinivision/hyena-operator/pkg/client/listers/infinivision.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HyenaClusterInformer provides access to a shared informer and lister for
// HyenaClusters.
type HyenaClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.HyenaClusterLister
}

type hyenaClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHyenaClusterInformer constructs a new informer for HyenaCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHyenaClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHyenaClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHyenaClusterInformer constructs a new informer for HyenaCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHyenaClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InfinivisionV1alpha1().HyenaClusters(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InfinivisionV1alpha1().HyenaClusters(namespace).Watch(options)
			},
		},
		&infinivisioncomv1alpha1.HyenaCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *hyenaClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHyenaClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *hyenaClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&infinivisioncomv1alpha1.HyenaCluster{}, f.defaultInformer)
}

func (f *hyenaClusterInformer) Lister() v1alpha1.HyenaClusterLister {
	return v1alpha1.NewHyenaClusterLister(f.Informer().GetIndexer())
}
